### PR TITLE
build(deps):upgrade to @mapbox/node-pre-gyp

### PR DESCRIPTION
**Pull request by devexdev**

### CODE REVIEW

**Comment by youming-lin** [comment]
Seems odd that ci didn't run for this PR

**Comment by youming-lin** [comment]
@jmeis Do we need to configure GH actions to run for forks?

**Comment by devexdev** [comment]
I was wondering if any tests would run.

**Comment by youming-lin** [comment]
Branch updated. Can you rebase?

**Comment by jmeis** [comment]
https://github.com/IBM/generator-ibm-cloud-assets/pull/211

fixed here ^

**Pull request closed without merging**
